# Generated by Django 4.2.10 on 2024-07-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('category', models.CharField()),
                ('place', models.CharField()),
                ('condition', models.CharField()),
                ('stock', models.PositiveIntegerField()),
                ('detail', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
    ]
