# Generated by Django 4.2.10 on 2024-08-04 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('text', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'equip',
            },
        ),
    ]
