# Generated by Django 4.2.10 on 2024-08-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_rename_name_equipment_equip_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='detail',
            new_name='text',
        ),
    ]
