# Generated by Django 4.2.10 on 2024-08-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
